name: Supermarket Billing CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      
      - name: Create PEM File
        run: |
          echo "${{ secrets.secret_key }}" > sheela-r.pem
          chmod 400 sheela-r.pem

      
      - name: Copy Project to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i sheela-r.pem -r * ec2-user@34.201.82.113:/home/ec2-user/supermarket-billing

      
      - name: Run Application
        run: |
          ssh -o StrictHostKeyChecking=no -i sheela-r.pem ec2-user@34.201.82.113 << 'EOF'
            cd /home/ec2-user/supermarket-billing

            # Install Python if not exists
            sudo yum install python3 -y

            # Install dependencies
            pip3 install -r requirements.txt

            # Stop old app if running
            pkill -f app.py || true

            # Run app in background
            nohup python3 app.py > output.log 2>&1 &
          EOF
