name: EC2 Deploy Pipeline

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

    
      - name: get pem file
        run: |
          echo "${{ secrets.sheela_key }}" > sheela-r.pem
          chmod 400 sheela-r.pem

     
      - name: cp app.py
        run: |
          scp -o StrictHostKeyChecking=no -i sheela-r.pem app.py ec2-user@43.204.22.22:/home/ec2-user/
          scp -o StrictHostKeyChecking=no -i sheela-r.pem requirements.txt ec2-user@43.204.22.22:/home/ec2-user/

  
      - name: Run application
        run: |
          ssh -o StrictHostKeyChecking=no -i sheela-r.pem ec2-user@43.204.22.22 "cd /home/ec2-user && python3 -m venv venv && source venv/bin/activate && pip3 install -r requirements.txt && python3 app.py" 
